### ISSUE TITLE
Compiling with Ubuntu 14.04 possible?

### ISSUE THREAD

**Issue by pw31** [ymgaq/AQ#88] opened 2018-03-04 11:10 UTC
Is it possible to compile AQ under Ubuntu 14.04 (GCC 4.8 x86_64-linux-gnu)?

I first tried to run the pre-compiled executable which says:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by AQ)
AQ: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by AQ)
AQ: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by AQ)
AQ: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by AQ)

Next, I tried to compile from source code. I followed the instructions to install brazier and tensorflow,
but now I have no clue how to proceed. The README.md is not very detailed here. In AQ-2.1.1/src there is a file called "BUILD" but I don't know what I should be next.

Thanks

**Comment by pw31** [comment] 2018-03-04 11:53
What worries me is that https://www.tensorflow.org/install/install_linux says only something about "Ubuntu 16.04 or higher". Does that mean that I cannot compile AQ on Ubuntu 14.04?

**Comment by ymgaq** [comment] 2018-03-06 01:36
I do not know about compiling with Ubuntu 14.04. 

However, the error seems to be caused by missing the library path or ```libstdc++``` itself.
Have you tried the following solutions?

[GLIBCXX_3.4.20 not found, how to fix this error?](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error)

[How to fix: [program name] /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version CXXABI_1.3.8' not found (required by [program name])](https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx)

**Comment by ymgaq** [comment] 2020-05-10 07:50
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.

**Closed by ymgaq** 2020-05-10 07:50 UTC
