### ISSUE TITLE
Bug: sometimes AQ will pass early if I go to another branch in Sabaki frontend

### ISSUE THREAD

**Issue by OneMoreSecond** [ymgaq/AQ#75] opened 2018-02-06 03:29 UTC
Environment:
AQ 2.1.1 mini_win release / windows10 / Intel i5-2450M / AMD HD6770M
Sabaki v0.33.2 frontend

Reproduction:
Let AQ play with another AQ, and manually branch several times on a board with over 100 moves.
It can be helped by going back one step and regenerating it.

Example:
[sgf file](https://github.com/ymgaq/AQ/files/1697612/new.zip)

console output:
![console](https://user-images.githubusercontent.com/16792948/35840005-854a051c-0b2e-11e8-8e30-6a5208779533.PNG)

Similar problem:
If I use Gogui frontend, the frontend will crash directly.
LeelaZero backend has similar problem.

**Comment by ymgaq** [comment] 2018-02-15 06:12
Maybe due to ```undo``` command bug. See #58 
The cause may be clarified if you show the command sent by the GUI client.

**Comment by ymgaq** [comment] 2020-05-10 07:49
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.

**Closed by ymgaq** 2020-05-10 07:49 UTC
