### ISSUE TITLE
Crashes when playing some engines

### ISSUE THREAD

**Issue by as0770** [ymgaq/AQ#73] opened 2018-02-04 09:40 UTC
Hello,

I am not sure if this is an AQ issue but I observed such a behaviour only with AQ. I play engine matches on Ubuntu 16.04 / 4 x Intel® Core™ i5-4210H CPU @ 2.90GHz, 8 GiB Ram and GeForce 840M/PCIe/SSE2

AQ works well against most engines, but crashes against Rayon and Oakfoam with the following error message:

```
W>> genmove w
2018-02-04 10:34:43.081034: E tensorflow/stream_executor/cuda/cuda_dnn.cc:371] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-02-04 10:34:43.081090: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-02-04 10:34:43.081099: F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
B>> final_score
B<< = B+74.5
B<< 
W>> final_score
B>> quit
B<< = 
B<< 
W>> quit
White program died
```
Likely some problems when running two engines on one GPU (ponder=off). This happens also with earlier versions.

**Comment by ymgaq** [comment] 2018-02-15 06:35
It may be caused by insufficient GPU memory. If you want to launch two programs, you must prepare
at least two graphics cards and use command ```CUDA_VISIBLE_DEVICES=0 ./AQ```, which allocates only single gpu device to AQ.

**Comment by as0770** [comment] 2018-02-15 17:26
So far I have only one GPU. Other engines also use the full GPU memory but it is no problem to run matches. I am not sure how the GPU memory is shared but I didn't observe a significant performance loss.

**Comment by hanysz** [comment] 2018-10-09 10:57
You can limit AQ to using 45% of your GPU memory (or some other fraction) by changing the source code and recompiling.  In theory you'd see a performance loss, but I don't believe it would make much difference (Leela Zero seems quite happy with only a few hundred megabytes, so why should AQ need 8 GB?)

Specifically, in search.cpp, change these lines:
```
                        Session* sess_p(NewSession(SessionOptions()));
                        GraphDef graph_p;

                        ReadBinaryProto(Env::Default(), sl_path, &graph_p);
                        graph::SetDefaultDevice(device_name, &graph_p);
                        sess_p->Create(graph_p);

                        Session* sess_v(NewSession(SessionOptions()));
                        GraphDef graph_v;
```

to this:

```

                        tensorflow::SessionOptions session_options;
                        session_options.config.mutable_gpu_options()->set_allow_growth(true);
                        session_options.config.mutable_gpu_options()->set_per_process_gpu_memory_fraction(0.45);
                        Session* sess_p(NewSession(session_options));
                        GraphDef graph_p;

                        ReadBinaryProto(Env::Default(), sl_path, &graph_p);
                        graph::SetDefaultDevice(device_name, &graph_p);
                        sess_p->Create(graph_p);

                        Session* sess_v(NewSession(session_options));
                        GraphDef graph_v;
```
(See https://stackoverflow.com/questions/44262837/how-to-limit-gpu-usage-in-tensorflow-r1-1-with-c-api and https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory)

**Comment by ymgaq** [comment] 2020-05-10 07:49
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.

**Closed by ymgaq** 2020-05-10 07:49 UTC
